version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t package

  build:
    commands:
      - echo "Zipping deployment package..."
      - cd package
      - zip -r ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_function.py

  post_build:
    commands:
      - echo "Updating Lambda function..."
      - aws lambda update-function-code --function-name surya-poc-1 --zip-file fileb://deployment_package.zip

artifacts:
  files:
    - deployment_package.zip
