version: 0.2

phases:
  install:
    # 'runtime-versions' is removed because Lambda compute uses the pre-selected image environment.
    commands:
      - echo "Installing dependencies..."
      # Install dependencies into the local 'lib' folder
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_function.py
  post_build:
    commands:
      - echo "Updating Lambda function..."
      # Updates the code for your specific function
      - aws lambda update-function-code --function-name surya-poc-1 --zip-file fileb://deployment_package.zip
      - echo "DONE!!"